# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f857ed9413d5f04e77e6f44751a3dfa82b6587517c1d22b6a028234b8b59215ce13d319ddf02e9bd6433b1997001872533980b88ec9fc163cb25eb1bd019ef12

test:
  secret_key_base: 1103f0a0b94f079f9182001bfd4f8c91b086afb4fd4a435e4d5a36f3883c6760666e3d9b66f3900da8ae7f5eb7fb2984f1594949971937868bc2dc2512c42517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
